triton-inference-server/model_analyzer

Dockerfile
README.md
docs/docker/overview.md
docs/helm/overview.md

Added a section to make it easier for users to try Model Analyzer by using a sample model from NGC, based on developer blog comment.

Added section on using a sample model.

---

model_analyzer/device/gpu_device.py
model_analyzer/monitor/dcgm/__init__.py
model_analyzer/monitor/dcgm/dcgm_agent.py
model_analyzer/monitor/dcgm/dcgm_field_helpers.py
model_analyzer/monitor/dcgm/dcgm_fields.py
model_analyzer/monitor/dcgm/dcgm_monitor.py
model_analyzer/monitor/dcgm/dcgm_structs.py
model_analyzer/monitor/dcgm/dcgm_value.py
model_analyzer/monitor/dcgm/model.py
model_analyzer/monitor/monitor.py
model_analyzer/monitor/nvml.py
tests/test_dcgm_monitor.py
tests/test_nvml_monitor.py

The files below are copied from the official DCGM Python 2 bindings. I made some modifications to the documentation, styling, and errors because of using Python 2 and to be consistent with the style that we are using for our code.
* `dcgm_agent.py`
* `dcgm_field_helpers.py`
* `dcgm_fields.py`
* `dcgm_structs.py`
* `dcgm_value.py`

Add DCGM Monitor

---

helm-chart/Chart.yaml
helm-chart/templates/_helpers.tpl
helm-chart/templates/job.yaml
helm-chart/values.yaml
model_analyzer/triton/client/client.py
qa/L0_unit_tests/test.sh
tests/mock_client.py
tests/test_triton_client.py

* Update helm charts
* Some test fixes
* Client bug fixes

Make model analyzer deployable with kubernetes

---

model_analyzer/output/output_table.py
tests/test_output_table.py

Changing the column padding in OutputTable changed the expected outputs in the tests.

Fix test_output_table test failure in main-dev

---

build_wheel.sh

Merge after [L0_copyright PR](https://github.com/triton-inference-server/model_analyzer/pull/43)

Fixed build_wheel.sh copyright

---

Dockerfile
model_analyzer/analyzer.py
model_analyzer/cli/cli.py
model_analyzer/entrypoint.py
model_analyzer/output/output_table.py
model_analyzer/record/record_aggregator.py
model_analyzer/triton/server/server_docker.py
qa/L0_analyze/test.sh
qa/L0_export_metrics/test.sh
qa/L0_server_launch_modes/test.sh
qa/common/util.sh
tests/test_record_aggregator.py

Before
```
Server Only:
Model                         Batch   Concurrency   Throughput(infer/sec)   Max GPU Utilization(%)   Max GPU Used Memory(MB)   Max GPU Free Memory(MB)  
triton-server                 0       0             0                       0.0                      228.0                     23991.0                  
Models:
Model                         Batch   Concurrency   Throughput(infer/sec)   Max GPU Utilization(%)   Max GPU Used Memory(MB)   Max GPU Free Memory(MB)  
classification_chestxray_v1   1       1             49.2                    37.0                     5186.0                    23359.0                  
```
After
```
Server Only:
Model           Batch   Concurrency   Max GPU Utilization(%)   Max GPU Used Memory(MB)   Max GPU Free Memory(MB)   GPU ID …
```

Add per GPU metrics in the output table

---

tests/mocks/mock_client.py
tests/mocks/mock_perf_analyzer.py
tests/mocks/mock_server.py
tests/mocks/mock_server_docker.py
tests/mocks/mock_server_local.py
tests/test_perf_analyzer.py
tests/test_triton_client.py
tests/test_triton_server.py

```
test_gpu_id (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_immediate_start_stop (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_record_memory (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_record_utilization (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_write (tests.test_file_writer.TestFileWriterMethods) ... ok
test_add_get_methods (tests.test_output_table.TestOutputTableMethods) ... ok
test_create_headers (tests.test_output_table.TestOutputTableMethods) ... ok
test_remove_methods (tests.test_output_table.TestOutputTableMethods) ... ok
test_set_width_methods (tests.test_output_table.TestOutputTableMethods) ... ok
test_to_formatted_string (tests.test_output_table.TestOutputTableMethods) ... ok
test_perf_analyzer_config …
```

Cleanup test mocks to inherit from MockBase

---

model_analyzer/cli/cli.py
model_analyzer/config/config.py
model_analyzer/config/config_enum.py
model_analyzer/config/config_field.py
model_analyzer/config/config_list_numeric.py
model_analyzer/config/config_list_string.py
model_analyzer/config/config_model.py
model_analyzer/config/config_object.py
model_analyzer/config/config_primitive.py
model_analyzer/config/config_protobuf_utils.py
model_analyzer/config/config_union.py
model_analyzer/config/config_value.py
model_analyzer/triton/model/model_config.py
tests/mocks/mock_client.py
tests/mocks/mock_model_config.py
tests/test_config.py
tests/test_model_config.py

~~This needs to be merged after #77 and #69.~~

Add support for parsing the config values from the Triton protobuf

---

model_analyzer/perf_analyzer/perf_analyzer.py
model_analyzer/result/result_manager.py

* Fix incorrect batch size value in the output table
* Fix the perf analyzer hang

Fix batch size value

---

model_analyzer/analyzer.py
model_analyzer/config/input/config.py
model_analyzer/config/input/config_field.py
model_analyzer/config/input/config_list_generic.py
model_analyzer/config/input/config_list_string.py
model_analyzer/config/input/objects/config_model.py
model_analyzer/config/run/run_search.py
model_analyzer/device/gpu_device_factory.py
model_analyzer/entrypoint.py
model_analyzer/model_manager.py
model_analyzer/monitor/dcgm/dcgm_monitor.py
model_analyzer/perf_analyzer/perf_analyzer.py
model_analyzer/plots/plot.py
model_analyzer/record/metrics_manager.py
model_analyzer/reports/pdf_report.py
model_analyzer/reports/report_manager.py
model_analyzer/result/result_manager.py
model_analyzer/triton/model/model_config.py
qa/L0_cpu/test.sh
tests/mocks/mock_matplotlib.py
tests/test_pdf_report.py
tests/test_plot.py
tests/test_report_manager.py

```
Models (Inference):                                                                                                                                                                                                                                       
Model                       Batch   Concurrency   Model Config Path               Instance Group   Preferred Batch Sizes   Satisfies Constraints                                                                                                          
resnet_v1_50_cpu_graphdef   1       4             resnet_v1_50_cpu_graphdef_i6    1/CPU            [2]                     Yes                                                                                                                            
resnet_v1_50_cpu_graphdef   1       2 …
```

Add support for CPU

---

model_analyzer/config/input/config_command_report.py
model_analyzer/reports/pdf_report.py
model_analyzer/reports/report_manager.py

Increased plot sizes in summary

---

build_wheel.sh
setup.py

Set default and fix DEPENDENCY_DIR bug in build_wheel

---

model_analyzer/entrypoint.py
model_analyzer/state/analyzer_state_manager.py
qa/L0_stability_perf/check_results.py
qa/L0_stability_perf/test.sh
qa/L0_stability_perf/test_config_generator.py
qa/L0_state_management/check_results.py
qa/L0_state_management/test.sh
tests/test_report_manager.py
tests/test_state_manager.py

* Added perf stability test to compare model analyzer against perf analyzer standalone
* Fixed bug where early exit from model analyzer might leave tritonserver running.

Added L0_stability_perf

---

model_analyzer/config/input/config_command_analyze.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/config/input/config_command_report.py
model_analyzer/config/input/config_defaults.py
model_analyzer/config/input/config_field.py
model_analyzer/config/input/config_utils.py
model_analyzer/entrypoint.py
model_analyzer/record/metrics_manager.py
tests/test_config.py
tests/test_report_manager.py
tests/test_run_search.py
tests/test_state_manager.py

Includes some required formatting changes

Added path validation to string inputs

---

Dockerfile

I tested the below command on both an amd64 and arm64 machine, and it worked correctly:
```
docker build --pull -t model-analyzer .
```

Add support for docker build building

---

.gitignore
model_analyzer/config/input/config_command_analyze.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/config/input/config_command_report.py

Scrub help options to have all short options appear first.

scrub help options

---

docs/quick_start.md

check out the new quick start here:
https://github.com/triton-inference-server/model_analyzer/blob/matthewkotila-update-docs/docs/quick_start.md

Update quick start

---

model_analyzer/config/run/run_search.py
model_analyzer/model_manager.py
tests/test_model_manager.py
tests/test_run_search.py

Added testing of all config combinations for model_manager

Add testing for model_manager

---

README.md

Updating the docs to include a parameter sweep overview

Update Readme to add parameter sweep overview

---

model_analyzer/analyzer.py
model_analyzer/triton/model/model_config.py

* Next command bug:
* accidentally used `--config_file` option (wrong) in suggested next command instead of `--config-file`
* Relative path bug:
* bug fix from #227

Fix next command bug and relative path bug

---

model_analyzer/perf_analyzer/perf_config.py

Update PA flags in MA to match actual PA flags

Update perf_analyzer_args to match perf_analyzer's actual set of args

---

tests/test_model_config.py

Adds unit test for work previously done in #256

Add unit test for relative model path symlink creation

---

Dockerfile
qa/L0_unit_tests/test.sh

Add testing and coverage package installation.

coverage report generation

---

docs/config_search.md

Clarify dynamic batching setting.

Update model config search doc to clarify dynamic batching setting

---

model_analyzer/config/generate/config_generator_interface.py
model_analyzer/config/generate/model_config_generator.py

This adds an interface to be used in future additions to the refactor dev branch

Add ConfigGeneratorInterface class

---

model_analyzer/model_manager.py

Disable loading of a model variant if 
- in `remote launch mode` and 
- not `reload_model_disable`

Conditionally load model variant

---

model_analyzer/analyzer.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/model_manager.py
tests/test_model_manager.py

Changes to Analyzer and ModelManager to support multi-model.

Multi model profile top level

---

docs/cli.md
docs/config.md
docs/quick_start.md
helm-chart/templates/config-map.yaml
model_analyzer/config/generate/model_config_generator.py
model_analyzer/result/result_manager.py
model_analyzer/triton/model/model_config.py
qa/L0_analyze/test.sh
qa/L0_export_metrics/test.sh
qa/L0_output_fields/test.sh
qa/L0_profile/check_results.py
qa/L0_quick_start/test.sh
qa/L0_results/test.sh
qa/L0_results/test_config_generator.py
qa/L0_server_launch_modes/test.sh
qa/L0_stability_metrics/test.sh
qa/L0_stability_result/test.sh
qa/L0_stability_steps/test.sh
qa/L0_state_management/check_results.py
tests/test_config.py
tests/test_model_config.py
tests/test_model_config_generator.py
tests/test_model_manager.py
tests/test_result_manager.py

Before, the default config was always run but it was still named <model>_config<#>.  Now it is named <model>_config_default.

Rename the default configuration to {model_name}_config_default

---

model_analyzer/plots/plot_manager.py
model_analyzer/reports/report_manager.py
model_analyzer/result/result_manager.py
tests/test_report_manager.py

Before and after reports and images are in the JIRA story

Include default config in summary reports

---

model_analyzer/reports/report_manager.py
tests/test_report_manager.py

- Update summary sentence to explicitly name the best config
- Update summary memory consumption sentence to fix CPU bug and to correctly reference plots
- Remove batch sizes from summary report

update summary report text

---

model_analyzer/config/generate/perf_analyzer_config_generator.py
model_analyzer/perf_analyzer/perf_analyzer.py
model_analyzer/perf_analyzer/perf_config.py
qa/L0_metrics/test_config_generator.py
tests/test_model_manager.py
tests/test_perf_analyzer.py
tests/test_perf_analyzer_config_generator.py

Replaces CLI parsing with reading the PA's output CSV file
Replaced (deprecated) perf_latency with perf_latency_p99 (which removes the annoying warning messages during analyze)
General boyscouting cleanup

Profile from csv

---

tests/common/test_utils.py
tests/test_result_heap.py
tests/test_run_config_result_comparator.py

Added some basic unit testing to RunConfigResultComparator + general clean up/organization of the unit testing

Add multi-model testing to RunConfigResultComparator

---

model_analyzer/result/run_config_result.py
tests/test_run_config_result.py

Added single and multi-model unit testing to RunConfigResult class
- Single model checking for all methods including boundary condition constraint checking
- Multi-model (2) checking for relevant methods

RunConfigResult unit testing

---

model_analyzer/result/result_manager.py
model_analyzer/result/results.py

- Added a check to determine if the profile checkpoint was sequential or concurrent
- Refactored compile_and_sort_results
Verified that analysis will run without crashing for sequential and concurrent profiles (concurrent profile output is not accurate)

Initial work for analysis of multi-model

---

model_analyzer/config/input/config_command.py
model_analyzer/config/input/yaml_config_validator.py
qa/L0_results/test_config_generator.py
tests/test_yaml_options.py

Add a yaml file validator that checks for underscore usage and against a list of valid options.

Add yaml config validator and testing

---

model_analyzer/result/constraint_manager.py
model_analyzer/result/run_config_result.py
tests/test_constraint_manager.py
tests/test_run_config_result.py

Adding unit testing for constraint manager
Adding support for multi-model constraints
Adding additional checking of constraints in RCR test class

Multi model constraint manager

---

experiments/config_command_experiment.py
experiments/generator_experiment_factory.py
model_analyzer/config/generate/search_config.py
model_analyzer/config/generate/search_dimensions.py
model_analyzer/config/generate/undirected_run_config_generator.py
tests/test_neighborhood.py
tests/test_search_config.py
tests/test_search_dimensions.py
tests/test_undirected_run_config_generator.py

- Created class SearchDimensions to hold the dimensions (instead of just using a list) and to associate them each with a key. This allows there to be multiple SearchDimension with the same name, but associated with different keys (and thus different models)
- Updated UndirectedRunConfigGenerator to support multi-model

Multi-model support for undirected algo

---

qa/L0_no_config_file/test.sh
qa/L0_no_config_file/test_config_generator.py
qa/L0_server_launch_modes/test.sh

New test that handles cases of no config.pbtxt file profiled for a model

Add testing for case of no model config file

---

experiments/evaluate_config_generator.py
experiments/generator_experiment_factory.py
experiments/main.py
model_analyzer/config/generate/brute_run_config_generator.py
model_analyzer/config/generate/quick_run_config_generator.py
model_analyzer/config/generate/run_config_generator_factory.py
tests/test_run_config_generator.py
tests/test_undirected_run_config_generator.py

RunConfigGenerator -> BruteRunConfigGenerator
UndirectedRunConfigGenerator -> QuickRunConfigGenerator

Rename run config generators

---

experiments/config_command_experiment.py
experiments/generator_experiment_factory.py
model_analyzer/config/generate/neighborhood.py
model_analyzer/config/generate/quick_run_config_generator.py
model_analyzer/config/generate/run_config_generator_factory.py
tests/test_neighborhood.py
tests/test_quick_run_config_generator.py

- Zero throughput instead of ignore and continue on bad PA result
- Change algorithm to be 2D for single-model
- Add variable step magnitude
- Update radius/magnitude/min_init to 3/4*5/3

Updates to quick algo

---

model_analyzer/analyzer.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/config/input/config_defaults.py
qa/L0_profile/test.sh
qa/common/util.sh
tests/test_analyzer.py
tests/test_cli.py

* Add new CLI option that skips generating summary reports after profile step.
* Add and fix test cases.

Add skip-summary-reports CLI option for profile

---

Dockerfile
model_analyzer/constants.py
qa/L0_type_checking/mypi.ini
qa/L0_type_checking/test.sh

Add an initial test to verify type checking in model analyzer

Add type checking test

---

model_analyzer/config/generate/brute_run_config_generator.py
tests/mocks/mock_run_configs.py
tests/test_model_manager.py

Don't generate non-default case for remote mode

Fix duplicate experiments

---

docs/config.md

Changes are on line 715-719
All other changes occurred when I saved the file. Everything looks fine in my output, but my formatter was not "happy" with how the file looked...

Updating config documentation to indicate some fields are YAML only

---

model_analyzer/result/model_config_measurement.py
model_analyzer/result/run_config_measurement.py
tests/test_model_config_measurement.py
tests/test_run_config_measurement.py

Removes objectives, constraints, and model weights from checkpoint
Updated unit testing to ensure these are not present
Ran locally and examined checkpoint; everything looks good

Removing objectives/weights/constraints from checkpoint

---

model_analyzer/config/generate/perf_analyzer_config_generator.py
tests/test_perf_analyzer_config_generator.py

... to be based on overall gain in window instead of consecutive measurements

Update gain calculation 

---

docs/checkpoints.md
docs/cli.md
docs/config.md
docs/install.md
docs/report.md

Fix all broken anchor links in the docs

Fix anchors

---

model_analyzer/config/generate/coordinate.py
model_analyzer/config/generate/coordinate_data.py
model_analyzer/config/generate/neighborhood.py
model_analyzer/config/generate/quick_run_config_generator.py
tests/test_coordinate.py

Porting [fix](https://github.com/triton-inference-server/model_analyzer/pull/491) from 22.08->main

Fix type checking failures in quick search algo

---

model_analyzer/result/constraint_manager.py
model_analyzer/result/model_config_measurement.py
model_analyzer/result/run_config_measurement.py
tests/test_constraint_manager.py
tests/test_run_config_measurement.py

New public method in RCM class: compare_constraints()
New static method in constraint_manager: constraint_failure_percentage()

New method to determine which RCM is closer to passing constraints

---

experiments/scripts/test_pa.py

Basic script to sweep through PA configurations, gather statistics about CPU/GPU usage as well as throughput/latency, and then print out results as a csv to stdout

Script to test PA

---

model_analyzer/config/input/config_command.py
tests/test_config.py

Allow ConfigCommandProfile/Analyze/Report to be copied

Add deepcopy to config_command

---

model_analyzer/config/generate/automatic_model_config_generator.py
model_analyzer/config/generate/base_model_config_generator.py
model_analyzer/config/generate/brute_run_config_generator.py
model_analyzer/config/generate/model_profile_spec.py
model_analyzer/config/generate/perf_analyzer_config_generator.py
model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py
model_analyzer/config/generate/quick_run_config_generator.py
model_analyzer/config/generate/run_config_generator_factory.py
model_analyzer/config/generate/search_config.py
model_analyzer/result/run_config_measurement.py
model_analyzer/triton/model/model_config.py
tests/test_model_config_generator.py
tests/test_quick_run_config_generator.py
tests/test_run_config_generator.py
tests/test_search_config.py

Don't turn on dynamic batching if it is not supported (or if sequence batching is already enabled)
Only search instance count in quick search for models that don't support batching

No batching support

---

model_analyzer/perf_analyzer/perf_analyzer.py
model_analyzer/record/types/gpu_total_memory.py
tests/test_perf_analyzer.py
tests/test_record_types.py

Captures new GPU metrics that PA provides and puts them into Records
Added a bunch of unit tests to cover the various scenarios of multi and sparse GPU reporting

Capture GPU metrics from PA

---

qa/L0_quick_search/check_results.py
qa/L0_quick_search/test.sh
qa/L0_quick_search/test_config_generator.py

This adds a L0 test that runs quick search on resnet and ensures the number of measurements taken is within the range of 20-80 (I observed 39 measurements on my local machine)

Added L0 quick search test

---

model_analyzer/analyzer.py
model_analyzer/config/generate/automatic_model_config_generator.py
model_analyzer/config/generate/base_model_config_generator.py
model_analyzer/config/generate/brute_run_config_generator.py
model_analyzer/config/generate/config_generator_interface.py
model_analyzer/config/generate/coordinate.py
model_analyzer/config/generate/coordinate_data.py
model_analyzer/config/generate/generator_utils.py
model_analyzer/config/generate/manual_model_config_generator.py
model_analyzer/config/generate/model_config_generator_factory.py
model_analyzer/config/generate/model_run_config_generator.py
model_analyzer/config/generate/model_variant_name_manager.py
model_analyzer/config/generate/neighborhood.py
model_analyzer/config/generate/perf_analyzer_config_generator.py
model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py
model_analyzer/config/generate/quick_run_config_generator.py
model_analyzer/config/generate/run_config_generator_factory.py
model_analyzer/config/generate/search_config.py
model_analyzer/config/generate/search_dimension.py
model_analyzer/config/generate/search_dimensions.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/result/result_manager.py
model_analyzer/result/run_config_measurement.py
qa/L0_type_checking/mypi.ini

- Add type hinting for generators folder
- Force type hinting for generators folder
- Disallow any partial type checked functions

Type check the generators folder

---

Dockerfile
experiments/experiment_plot.py
format.py
model_analyzer/config/generate/automatic_model_config_generator.py
model_analyzer/config/generate/base_model_config_generator.py
model_analyzer/config/generate/brute_run_config_generator.py
model_analyzer/config/generate/config_generator_interface.py
model_analyzer/config/generate/coordinate.py
model_analyzer/config/generate/coordinate_data.py
model_analyzer/config/generate/generator_utils.py
model_analyzer/config/generate/manual_model_config_generator.py
model_analyzer/config/generate/model_config_generator_factory.py
model_analyzer/config/generate/model_run_config_generator.py
model_analyzer/config/generate/neighborhood.py
model_analyzer/config/generate/run_config_generator_factory.py
model_analyzer/config/generate/search_config.py
model_analyzer/config/generate/search_dimension.py
model_analyzer/config/generate/search_dimensions.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/plots/simple_plot.py
model_analyzer/result/result_manager.py
model_analyzer/result/run_config_measurement.py
qa/L0_custom_ops/test_config_generator.py
setup.py
tests/test_cli.py
tests/test_model_config_measurement.py
tests/test_state_manager.py

Install yapf 0.32.0 in Docker container
Update format.py to expect 0.32.0
Reformat all files in the repo

Re-format all files with yapf

---

README.md
docs/config.md
docs/config_search.md
docs/install.md
model_analyzer/config/input/config_command_profile.py

Also, removing ```Will be ignored if server-launch-mode is not 'remote'``` from the 3 places it doesn't belong

Add early access documentation for multi-model

---

README.md
docs/README.md

This fixes the copyrights test

Fixing README copyrights

---

model_analyzer/record/gpu_record.py
model_analyzer/record/record.py
model_analyzer/record/types/cpu_available_ram.py
model_analyzer/record/types/cpu_used_ram.py
model_analyzer/record/types/gpu_free_memory.py
model_analyzer/record/types/gpu_power_usage.py
model_analyzer/record/types/gpu_total_memory.py
model_analyzer/record/types/gpu_used_memory.py
model_analyzer/record/types/gpu_utilization.py
model_analyzer/record/types/perf_client_response_wait.py
model_analyzer/record/types/perf_client_send_recv.py
model_analyzer/record/types/perf_latency.py
model_analyzer/record/types/perf_latency_avg.py
model_analyzer/record/types/perf_latency_p90.py
model_analyzer/record/types/perf_latency_p95.py
model_analyzer/record/types/perf_latency_p99.py
model_analyzer/record/types/perf_server_compute_infer.py
model_analyzer/record/types/perf_server_compute_input.py
model_analyzer/record/types/perf_server_compute_output.py
model_analyzer/record/types/perf_server_queue.py
model_analyzer/record/types/perf_throughput.py
model_analyzer/reports/report_manager.py
model_analyzer/result/model_config_measurement.py
model_analyzer/result/run_config_measurement.py
tests/test_model_config_measurement.py
tests/test_record_types.py
tests/test_report_manager.py
tests/test_run_config_measurement.py

Updated result_summary.pdf statement to look like: 
With a gain: ![image](https://user-images.githubusercontent.com/92820864/201765167-d2f8301d-f9e3-4f60-aae7-c8dcae31ca14.png)
When default is the best: ![image](https://user-images.githubusercontent.com/92820864/201765522-e025c714-db5c-44ef-ac88-fc6082e9da06.png)

Update summary report message

---

model_analyzer/triton/model/model_config.py
tests/test_model_config.py

Adds new methods to check if the model's platform is ensemble and to change the submodel variant names.
Note: This is merging on to the ensemble branch, not main

Add ensemble support to ModelConfig

---

model_analyzer/config/generate/base_model_config_generator.py
model_analyzer/config/generate/quick_run_config_generator.py
tests/test_quick_run_config_generator.py

Generate RunConfigs for the non-default configs of ensemble models.
I've added unit testing and I have run an ensemble model through the profile step and it did complete successfully:

Ensemble Non-default Config Generation

---

requirements.txt

This reverts commit 4b474ccd938efbbf1d8a398a1d9a2df6d9d67cde.

Revert "Updating 'requirements.txt' (#591)"

---

docs/config_search.md
model_analyzer/config/input/config_command.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/model_manager.py
qa/L0_quick_search_multi_model/test.sh
tests/test_config.py
tests/test_model_manager.py

Includes updated error messages, unit/L0 testing and documentation

Make quick the default RCS for ensemble and multi-model

---

model_analyzer/triton/server/server_docker.py

Fix for https://github.com/triton-inference-server/model_analyzer/issues/607

Fix support for custom server docker image

---

docs/config.md
docs/mm_quick_start.md

Fix typos, formatting, add ToC, etc...

Config.md cleanup

---

docs/config.md
model_analyzer/config/input/config_command_profile.py
tests/test_cli.py
tests/test_config.py

Limited unit testing for this, but I have a BLS model (pipeline) with two submodels (vae, text encoder) and have verified that the command works as intended.

Add --bls-composing-models config option

---

model_analyzer/config/generate/quick_run_config_generator.py
tests/test_quick_run_config_generator.py

Includes unit testing and I've run this on FaceDetect and confirmed it is working.

Logic for non-default BLS profiling

---

model_analyzer/reports/report_manager.py
tests/common/bls-ckpt/README
tests/test_bls_report_manager.py
tests/test_quick_run_config_generator.py

Logic for detailed reporting w/ a unit test.
Relevant section of the detailed report:

BLS Detailed Reporting

---

model_analyzer/config/input/config_command.py
tests/test_config.py

Also, fixed some misspellings the spell checker found

Checking for illegal cases with BLS

---

model_analyzer/plots/detailed_plot.py
model_analyzer/reports/report_manager.py

Adds support for detailed reporting via request rate. Here's what the new detailed report looks like:

Request Rate in Detailed Report

---

model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py

There's no unit testing, so I've run this on a live model (add_sub). Here are the results:

Integrating concurrency search into quick search

---

docs/config.md
docs/report.md
model_analyzer/analyzer.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/config/input/config_defaults.py
qa/L0_profile/test.sh
tests/test_analyzer.py
tests/test_cli.py

This reverts commit b30e0617dceef66a1205689e1eb40f010db830b9 because it caused a wheeltamer issue

Revert "Create detailed reports after profile (#691)"

---

model_analyzer/plots/simple_plot.py
model_analyzer/result/constraint_manager.py
model_analyzer/result/model_constraints.py
model_analyzer/result/result_manager.py
model_analyzer/result/run_config_result.py
tests/test_constraint_manager.py
tests/test_coordinate_data.py
tests/test_model_constraints.py
tests/test_plot_manager.py
tests/test_result_manager.py
tests/test_run_config_result.py
tests/test_sorted_results.py

With the [Clang upgrade in our formatter](https://github.com/triton-inference-server/common/pull/94), we are running the formatter on all Triton repos. If you would like to use the formatting tool in this repo, feel free to approve this PR.

Auto-formatting

---

model_analyzer/analyzer.py
model_analyzer/triton/client/client.py
model_analyzer/triton/client/grpc_client.py
model_analyzer/triton/client/http_client.py

Check and print a warning message if there are models other than the one being profiled on the remote server.

Check if other models on server

---

model_analyzer/config/generate/generator_utils.py
model_analyzer/config/generate/perf_analyzer_config_generator.py
model_analyzer/config/input/config_command_profile.py
model_analyzer/config/input/config_defaults.py
model_analyzer/perf_analyzer/perf_analyzer.py
model_analyzer/perf_analyzer/perf_config.py
model_analyzer/record/types/avg_first_token_latency.py
model_analyzer/record/types/avg_token_to_token_latency.py
model_analyzer/result/result_table_manager.py
tests/test_result_table_manager.py

Changes to get summary reports outputting correctly for LLM models.
Here is an example output:
```Models (Inference):
Model   Batch   Periodic Concurrency   Request Period   Text Input Length   Max Token Count   Model Config Path   Instance Group   Avg First Token-to-Token latency (ms)   Avg Token-to-Token latency (ms)  
vllm    1       16:32:8                1                10                  8                 vllm_config_0       1:GPU            54.0                                    21.1                             
vllm    1       16:32:16               1                10                  8                 vllm_config_0       1:GPU            53.7                                    21.7                             
vllm    1       16:64:8                1                10 …
```

Changes to get LLM summary reports working

---

model_analyzer/record/metrics_manager.py

Cherry picking the change into 24.01 since the matching change was cherry picked into the core repo

Fix loading of composing models for ensembles (#810)

---

model_analyzer/record/metrics_manager.py

From [Issue #116](https://github.com/triton-inference-server/model_analyzer/issues/816)

Fix bug in GPU metrics capture logic

---

docs/config.md
model_analyzer/config/input/config_command_profile.py

Add the three new LLM metrics to the list of possible constraints and updated documentation.

Update constraints for LLMs

---

README.md
docs/config.md
docs/config_search.md

Adding documentation for LLM Metrics in MA.

Adding LLM Metrics to MA documentation

---

Dockerfile

Update `Dockerfile` configuration.
references: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

Update `Dockerfile` configuration.

---

model_analyzer/analyzer.py
model_analyzer/config/generate/optuna_plus_concurrency_sweep_run_config_generator.py
model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py
model_analyzer/config/generate/run_config_generator_factory.py
model_analyzer/config/generate/search_parameters.py
model_analyzer/model_manager.py
tests/test_model_manager.py

Initial code to create an Optuna RCG factory entry. Have successfully run two live models through optuna (add_sub/resnet).

Creating Optuna RCG factory

---

model_analyzer/config/generate/optuna_run_config_generator.py

Check that model supports dynamic batching before adding in when creating param_combos.

Check that model supports dynamic batching when creating param_combo

---

README.md
docs/config.md
docs/config_search.md
docs/ensemble_quick_start.md

Add documentation about new search mode, CLI/Config options, and example output.

Documentation update for Optuna (alpha release)

---

README.md

Update README for 24.07 release.

Update README for 24.07 branch

---

model_analyzer/config/generate/optuna_run_config_generator.py
model_analyzer/config/generate/search_parameters.py
tests/test_optuna_run_config_generator.py
tests/test_search_parameters.py

PR to support request-rate parameter in optuna mode.

Add request rate parameter for optuna search

---

README.md
docs/cli.md
docs/config_search.md
docs/model_types.md

This covers the following changes requested in the VDR:
- Define commonly used terminology
- Create a support matrix
- Divide search mode and model types
- Update examples on CLI page

Updating documentation based on VDR

---

docs/launch_modes.md

Adding note to warn user about custom backend in docker mode

Adding note to warn user about custom backend in docker mode

---

README.md

Update README.md for 24.09 Release

Update README for r24.09

---

README.md

Updates the README file for the 24.10 Triton release.

Update README for r24.10
