triton-inference-server/model_analyzer

model_analyzer/output/output_table.py, model_analyzer/perf_analyzer/perf_config.py, tests/test_output_table.py, tests/test_perf_analyzer.py
Columns of table can now be separated with commas or any other string. Default column padding also changed to None.
=> Add a separator to OutputTable.to_string_formatter

model_analyzer/monitor/dcgm/dcgm_monitor.py, model_analyzer/record/gpu_utilization.py, tests/test_dcgm_monitor.py
```
python3 -m unittest discover -v                                                    
test_record_memory (tests.test_dcgm_monitor.TestDCGMMonitor) ... lib/python3.8/multiprocessing/pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=1>
_warn(f"unclosed running multiprocessing pool {selfrm TEST_LOG}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_record_utilization (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_write (tests.test_file_writer.TestFileWriterMethods) ... ok
test_add_get_methods (tests.test_output_table.TestOutputTableMethods) ... ok
test_create_headers (tests.test_output_table.TestOutputTableMethods) ... ok
test_remove_methods …
```
=> Add GPUUtilization

model_analyzer/analyzer.py, model_analyzer/cli/cli.py, model_analyzer/device/gpu_device_factory.py, model_analyzer/entrypoint.py, model_analyzer/monitor/dcgm/dcgm_monitor.py, model_analyzer/monitor/monitor.py, model_analyzer/perf_analyzer/perf_analyzer.py, model_analyzer/triton/server/server_docker.py, model_analyzer/triton/server/server_factory.py, requirements.txt, tests/test_dcgm_monitor.py, tests/test_triton_client.py, tests/test_triton_server.py
* Adds a `--gpus` flag to control the GPUs being used for analysis.
* Adds checks to make sure that Model Analyzer and Triton are using the same GPUs
* Fixes minor bug if the `start_monitoring_metrics` and `stop_monitoring_metrics` are called without any delay.
```
test_gpu_id (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_immediate_start_stop (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_record_memory (tests.test_dcgm_monitor.TestDCGMMonitor) ... /home/itabrizian/miniconda3/envs/nvml-py/lib/python3.8/multiprocessing/pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=1>
_warn(f"unclosed running multiprocessing pool {self!r}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok …
```
=> Add --gpus flag

model_analyzer/analyzer.py, model_analyzer/cli/cli.py, model_analyzer/device/gpu_device.py, model_analyzer/entrypoint.py, model_analyzer/monitor/monitor.py, model_analyzer/perf_analyzer/perf_analyzer.py, model_analyzer/record/perf_throughput.py, model_analyzer/triton/client/client.py, model_analyzer/triton/server/server_docker.py, model_analyzer/triton/server/server_factory.py, model_analyzer/triton/server/server_local.py
```
model-analyzer -m /home/.../Code/triton/model_analyzer/examples/quick-start/ -n add_sub --triton-launch-mode docker --log=INFO
2020-11-25 21:00:56.308 INFO[entrypoint.py:317] Triton Model Analyzer started Namespace(batch_sizes='1', client_protocol='grpc', concurrency='1', duration_seconds=5, export=False, export_path='.', filename_model='metrics-model.csv', filename_server_only='metrics-server-only.csv', gpus=['all'], log_level='INFO', max_retries=100, model_names='add_sub', model_repository='/home/itabrizian/Code/triton/model_analyzer/examples/quick-start/', monitoring_interval=0.01, perf_analyzer_path='perf_analyzer', triton_grpc_endpoint='localhost:8001', triton_http_endpoint='localhost:8000', triton_launch_mode='docker', triton_metrics_url='http://localhost:8002/metrics', …
```
=> Add logging and support for graceful termination

build_wheel.sh, setup.py
Build process:
```
asramesh@asramesh-dt:~/model_analyzer$ ./build_wheel.sh perf_analyzer true
Thu Nov 26 00:31:34 PST 2020 : === Building wheel
...
adding 'model_analyzer-1.0.0.dev0.dist-info/*'
removing build/bdist.linux-x86_64/wheel
Thu Nov 26 00:31:38 PST 2020 : === Output wheel file is in: /home/asramesh/model_analyzer/wheels
asramesh@asramesh-dt:~/model_analyzer$ ls -l wheels
total 2852
-rw------- 1 asramesh hardware 2905629 Nov 26 00:31 model_analyzer-1.0.0.dev0-py3-none-manylinux1_x86_64.whl
-rw------- 1 asramesh hardware       0 Nov 26 00:31 stamp.whl
```
Install process:  (Inside build container)
```
root@asramesh-dt:/opt/triton-model-analyzer# which model-analyzer
root@asramesh-dt:/opt/triton-model-analyzer# which perf_analyzer …
```
=> Build model-analyzer as a manylinux1_x86_64.whl

model_analyzer/entrypoint.py, model_analyzer/triton/server/server_docker.py, model_analyzer/triton/server/server_local.py, qa/L0_server_launch_modes/test.sh, tests/mock_api_error.py, tests/mock_perf_analyzer.py, tests/mock_server_docker.py, tests/mock_server_local.py, tests/test_triton_server.py
Some minor issues were fixed when launching Model Analyzer using Docker:
1. Container name already exists
2. Better error printing when the port is already allocated
=> Fix minor issues when launching using Docker

README.md, model_analyzer/analyzer.py, model_analyzer/cli/cli.py, model_analyzer/config/__init__.py, model_analyzer/config/config.py, model_analyzer/config/config_field.py, model_analyzer/entrypoint.py, qa/L0_doa/test.sh, qa/L0_unit_tests/test.sh, requirements.txt, tests/mocks/mock_config.py, tests/test_triton_config.py
Added Model Analyzer Config.  Currently, supports all the flags supported by the current version of Model Analyzer. The priority is with the CLI and then with the Config file as mentioned in the engineering doc.
An example configuration looks like below:
```yaml
model_repository: /data/inferenceserver/20.11dev/tf_model_store/
export: true
triton_launch_mode: docker
model_names: vgg_16_graphdef
concurrency: 1
triton_http_endpoint: localhost:8030
triton_grpc_endpoint: localhost:8040
triton_metrics_url: http://localhost:8090/metrics
batch_sizes: 2
```
=> Add Model Analyzer config

model_analyzer/cli/cli.py, model_analyzer/config/config.py, model_analyzer/config/config_field.py, model_analyzer/config/config_list_generic.py, model_analyzer/config/config_list_numeric.py, model_analyzer/config/config_list_string.py, model_analyzer/config/config_object.py, model_analyzer/config/config_primitive.py, model_analyzer/config/config_value.py, model_analyzer/constants.py, model_analyzer/entrypoint.py, tests/test_config.py, tests/test_triton_config.py
The model config is now able to parse all the various configurations below:
```yaml
model_names:
-
vgg_16_graphdef:
parameters:
concurrency:
- 1
- 2
- 3
- 4
- vgg_19_graphdef
```
```yaml
model_names:
vgg_16_graphdef:
parameters:
concurrency:
- 1
- 2
- 3
- 4
vgg_19_graphdef:
parameters:
concurrency:
- 1
- 2
- 3
- 4
batch_sizes:
start: 2
end: 6
step: 2
```
```yaml
model_names:
-
vgg_16_graphdef:
parameters:
concurrency:
- 1
- 2
- 3
- 4
objectives:
- throughput
- gpu_memory
constraints:
gpu_memory:
max: 80
- vgg_19_graphdef
```
This PR only addresses the parsing of the configuration. Integrating this into the Model Analyzer will be addressed in a future PR.
I tried to make the design as flexible as possible so that we can support all the various nested configurations possible.
I addressed …
=> Add constraints to Model Config

model_analyzer/config/config.py, model_analyzer/config/config_field.py, model_analyzer/config/config_list_generic.py, model_analyzer/config/config_list_numeric.py, model_analyzer/config/config_list_string.py, model_analyzer/config/config_model.py, model_analyzer/config/config_object.py, model_analyzer/config/config_primitive.py, model_analyzer/config/config_value.py, model_analyzer/entrypoint.py, tests/common/test_result_collector.py, tests/test_config.py, tests/test_cpu_monitor.py, tests/test_dcgm_monitor.py, tests/test_file_writer.py, tests/test_output_table.py, tests/test_perf_analyzer.py, tests/test_record_aggregator.py, tests/test_triton_client.py, tests/test_triton_server.py
Previously the following problematic configs were accepted in the Model Analyzer Config:
```yaml
batch_sizes: []
```
```yaml
concurrency:
start: 1
stop: 10
undefined_key: 12
```
Now an error stating that this is an invalid config is shown.
```
ERROR:root:Model Analyzer encountered an error: Can't set value { [] } for field batch_sizes.
```
I've also unified the output of model names. Model names can be represented in various different formats and parsing different variations could be difficult. Now, model_names will always be a list of `ConfigModel`.
=> Add validation to Model Analyzer config

model_analyzer/config/config.py, model_analyzer/config/config_enum.py, model_analyzer/config/config_field.py, model_analyzer/config/config_list_generic.py, model_analyzer/config/config_list_numeric.py, model_analyzer/config/config_list_string.py, model_analyzer/config/config_object.py, model_analyzer/config/config_primitive.py, model_analyzer/config/config_status.py, model_analyzer/config/config_union.py, model_analyzer/config/config_value.py, model_analyzer/constants.py, tests/test_config.py, tests/test_model_config.py
Some example error messages:
```
Value "{'a': 'b'}" cannot be set for field "my_field". This field allows multiple types of values. You only need to fix one of the errors below:
* If a dictionary is used for field "my_field", it should only contain "start" and "stop" key with an optional "step" key. Currently, contains ['a'].
* Value "{'a': 'b'}" for field "my_field" should be a primitive type.
```    
```
The value for field "my_field" should be a list and the length must be larger than zero.
```
```
Can't set the value for field "model_names". The error below occured when parsing the config:
Value "{'vgg_19_graphdef': {'model_config_parameters': {'instance_group': [{'kind': ['KIND_CPU', 'KIND_GPU', 'KIND_DPU'], 'count': 1}]}}}" cannot be set for field "model_names". This field allows …
```
=> Improve config error messages

qa/L0_config/test.sh, qa/L0_config_range/test.sh, qa/L0_config_search/test.sh, qa/L0_custom_flags/test.sh, qa/L0_output_fields/test.sh
There was an off-by-one error in the 5 test.sh scripts which the number of .yml config files was checked incorrectly with < 0. The checks are updated to use <= 0.
=> Corrected 5 test.sh scripts to check for the existence of config file(s) correctly

model_analyzer/entrypoint.py, model_analyzer/triton/server/server_docker.py, model_analyzer/triton/server/server_factory.py, model_analyzer/triton/server/server_local.py, qa/L0_server_launch_modes/test.sh, tests/mocks/mock_gpu_device_factory.py, tests/mocks/mock_server_docker.py, tests/mocks/mock_server_local.py, tests/test_triton_server.py
If the user sets the `gpus: []` config for model-analyzer, then this implies the model-analyzer should not use any GPU. This is a fix that the model-analyzer will launch the triton server without any GPU, when that config is present. 
This pull request also unifies how the `gpus` config is processed between local and docker mode. Previously, they are scattered across `entrypoint.py`, `server_local.py` and `server_docker.py`. This unification will process the `gpus` config inside `server_local.py` and `server_docker.py` using the `GPUDeviceFactory` class in `gpu_device_factory.py` which will return a list of GPU UUIDs that should be used based on the `gpus` config. Then, the `server_local.py` and `server_docker.py` will launch the server according to the returned list of GPU UUIDs.
=> Fix model analyzer to launch server with no GPU when empty gpus config is used

Dockerfile
Also adjusted installation method to be same as [build.py](https://github.com/triton-inference-server/server/blob/main/build.py)
=> Update DCGM version for model_analyzer

tests/test_record_types.py
The record types in the model-analyzer.record.types package is contextual when it uses 'less than' (<) and 'greater than' (>) operators.  The 'less than' and 'greater than' operators are overloaded to mean 'worse than' and 'better than' respectively.
- Some record types treat MORE as better (eg, gpu_free_memory, cpu_available_ram)
- Other record types treat LESS as better (eg, gpu_used_memory, cpu_used_ram)
So, when comparing two objects of type cpu_used_ram  12 > 13 is actually true, since 12 'is better than' 13.
Based on this context, the code is working fine.
-------------------------------------------------------------------------------------------------------
However, not all record types were being tested.  
This PR closes the gap so that all record types are tested in two ways:
1. …
=> Test all record types

model_analyzer/cli/cli.py, qa/L0_doa/test.sh, tests/test_cli.py
model analyzer should print the help message when no arguments are provided, rather than raising an exception like before
before:
```
$ model-analyzer
Traceback (most recent call last):
File "/usr/local/bin/model-analyzer", line 33, in <module>
sys.exit(load_entry_point('triton-model-analyzer', 'console_scripts', 'model-analyzer')())
File "/opt/triton-model-analyzer/model_analyzer/entrypoint.py", line 274, in main
args, config = get_cli_and_config_options()
File "/opt/triton-model-analyzer/model_analyzer/entrypoint.py", line 211, in get_cli_and_config_options
return cli.parse()
File "/opt/triton-model-analyzer/model_analyzer/cli/cli.py", line 137, in parse
config = self._subcommand_configs[args.subcommand]
KeyError: None
```
after:
```
$ model-analyzer
usage: model-analyzer [-h] [-q] [-v] …
```
=> Print help when no args

docs/quick_start.md
There's an error in the quick start. The commands above the docker run command set the user's current working directory to be the repo root. The docker run command needs to be modified to work when user is cd'd to repo root
=> Fix quick start error

model_analyzer/analyzer.py, qa/L0_custom_ops/test.sh, tests/test_analyzer.py
This PR adds suggestions to the user on what command to run next after both the `profile` and `analyze` commands
i.e.
* after `profile` command is run, the `analyze` command is pre-created and output to the user in the shell for them to copy and paste/run
* after `analyze` command is run, the `report` command is given
=> Add next commands to cli output

Dockerfile
Removing the libgfortran5 installation from the dockerfile. This is the job of the triton server codebase.
=> Remove libgfortran5 installation

docs/config.md, model_analyzer/perf_analyzer/perf_config.py, tests/test_perf_analyzer.py
`perf_analyzer_flags` `shape` option of model analyzer config currently supports list of strings, but not a non-list single string. It should support a non-list single string. This PR adds that support
Example of list of strings (supported before and after PR--unaffected):
```
...
perf_analyzer_flags:
shape:
- INPUT0:2
- INPUT1:2
...
```
Example of non-list single string (not supported before PR, supported after PR):
```
...
perf_analyzer_flags:
shape: INPUT0:2
...
```
=> Fix perf analyzer single shape non list arg usage

model_analyzer/config/run/run_config_generator.py, model_analyzer/model_manager.py, qa/L0_config/config_generator.py, qa/L0_config_search/test_config_generator.py, qa/L0_metrics/test.sh, qa/L0_state_management/check_results.py, tests/mocks/mock_config.py, tests/mocks/mock_run_configs.py, tests/test_model_manager.py, tests/test_record_types.py, tests/test_run_config_generator.py
Run the default config (the unmodified model_config passed to MA) on all MA profile runs.
Also updated test_model_manager tests to use a dict of expected values ranges instead of lists, and added many new tests to lock up the behavior.
=> Always run default config

model_analyzer/model_manager.py, model_analyzer/triton/model/model_config.py
Before, we would link model variant i{N} to i{N-1}. The first model variant is a deep copy of the source model. With large runs, this would break as unix apparently only allows a symlink chain length maximum of 40.
After this PR, all model variants after the first link directly to the first model variant. The first model variant is still a deep copy of the source model. Now there is no symlink chain. Each (non-first) variant just points directly to first variant.
=> Link subsequent model variants to first model variant

tests/common/test_utils.py, tests/test_model_manager.py, tests/test_report_manager.py, tests/test_run_config_generator.py, tests/test_run_search.py, tests/test_state_manager.py
This is the issue:
File "/usr/lib/python3.8/gettext.py", line 411, in _parse
magic = unpack('<I', buf[:4])[0]
It expects the buffer to be of type byte and a minimum length of 4. Still not sure why this only complains from vscode, but it's simple enough to fix:
- create_yaml() to convert strings and append blanks (if too short)
I have observed all unit tests passing and interactive debug is now working in vscode.
=> Fixing errors in unit tests when running from vscode

model_analyzer/triton/server/server_config.py, model_analyzer/triton/server/server_local.py, qa/L0_custom_flags/test_config_generator.py
Fixes issue: https://github.com/triton-inference-server/model_analyzer/issues/279
Feature: https://github.com/triton-inference-server/tensorflow_backend#--backend-configtensorflowversionint
Exercises this server code: https://github.com/triton-inference-server/server/blob/main/src/servers/main.cc#L1132-L1159
Problem: The MA code was not handling properly the case where TWO equals signs exist
(eg, `--backend-config=tensorflow,version=2`)
Before, the code accidentally split on both equals signs:
```
['tritonserver',  '--backend-config', 'tensorflow,version', '2']
```
The fix is to 
1) split on the argument list by spaces
2) Then for each of those arguments, split on the `first` equals sign
After the fix, the code splits on only the first equals sign:
```
['tritonserver', '--backend-config', …
```
=> Fix argument parsing

tests/test_model_manager.py
This adds tests that currently pass in main but FAIL in the profile-refactor side branch. I am blocked on fixing the tests until some of the RCG refactor is done, but I wanted to at least keep the tests
For the tests, I am no longer mocking out add_measurements(). Instead by default I am returning valid measurements with acceptable perf_throughput gain.  For the new tests, in one case I return no measurement. In the other case, I return measurements with invalid gain.
=> Add tests for early exits of run_search

model_analyzer/config/run/run_config_generator.py, model_analyzer/triton/model/model_config.py, qa/L0_profile/check_results.py, qa/L0_quick_start/test.sh, tests/test_model_config.py, tests/test_run_config_generator.py
Changing the output directory naming convention to remove the ambiguous i.
=> Rename output directories to use config instead of i

qa/L0_perf_analyzer/test.sh, qa/L0_perf_analyzer/test_config_generator.py
This test was previously failing because the wrong checker function from `check_results.py` was being used. Now the correct checker function is being used 👍
=> Fix L0_perf_analyzer test bug

qa/L0_stability_metrics/check_results.py
Convert test from comparing values to simply test for non-zero values.
Due to the change in requirements for this L0 test, the `tolerance` value was removed.
Since we do not currently have a way to test our tests, this is a list of values I tested manually.
```
[0.0]       # fail
[0.000000]  # fail
[0.000001]  # pass
[1.0]       # pass
['0']       # fail
['zero']    # fail
['1']       # fail
['one']     # fail
['']        # fail
```
=> Fix L0_stability_metrics

docs/launch_modes.md, docs/quick_start.md
The ask was to add a table to the launch mode docs showing tradeoffs between various model analyzer launch modes to help users understand which launch mode they may want to use.
=> Improve launch mode docs

model_analyzer/result/result_manager.py, tests/test_result_manager.py
observe that there are backend parameters in the triton config for this model:
```
...
parameters: {
key: "add_sub_key_1"
value: {
string_value:"add_sub_value_1"
}
}
parameters: {
key:"add_sub_key_2"
value: {
string_value:"add_sub_value_2"
}
}
...
```
observe that the backend parameters from the triton config *don't* appear in the model analyzer table output:
```
Models (Inference):
Model     Model Config Path   p99 Latency (ms)
add_sub   add_sub_config2     0.9
add_sub   add_sub_config1     0.9
add_sub   add_sub_config0     0.8
```
same model config as before:
```
...
parameters: {
key: "add_sub_key_1"
value: {
string_value:"add_sub_value_1"
}
}
parameters: {
key:"add_sub_key_2"
value: {
string_value:"add_sub_value_2"
}
}
...
```
observe that the backend parameters from the triton config …
=> Add model config backend parameters to metrics model inference output

model_analyzer/config/input/config_command_profile.py, model_analyzer/entrypoint.py, qa/L0_server_launch_modes/test_config_generator.py
Much like validating the `triton_server_path in local launch mode`, the PR is validating `triton_install_path in c_api launch mode`.
=> Validate `triton_install_path` in c_api launch mode only

model_analyzer/perf_analyzer/perf_analyzer.py, tests/test_perf_analyzer.py
Example data:
Pass [1] throughput: 5.80911e+07 infer/sec. Avg latency: 18023 usec (std 699 usec)
Before this change that data would be observed as 5.8 inferences/second instead of 58091100 inferences/second. This change fixes it
=> Support scientific notation PA throughput

model_analyzer/entrypoint.py, model_analyzer/triton/client/client_factory.py, model_analyzer/triton/client/grpc_client.py, model_analyzer/triton/client/http_client.py, nginx.conf, requirements.txt
This is a duplicate of https://github.com/triton-inference-server/model_analyzer/pull/326 so that we can get it merged since Tanmay is offline right now
=> Pass SSL options to python triton client instantiations

model_analyzer/result/result_manager.py
Current behavior:
- Report step will print errors, but not stop. Then it will raise a totally unrelated and confusing error
- Analyze step will print a ton of warnings, one of which (in the middle) actually says that the requested data is missing. Then it will print out empty data tables, and give an invalid "next step" command for the report step
New behavior:
- Both report and analyze will fail very early on if requested model or model variant data does not exist
Top 2 images are before changes. Bottom 2 are after changes.
=> Explicitly fail if data missing in analyze/report steps

model_analyzer/plots/detailed_plot.py, model_analyzer/result/result_manager.py
1) View the labels inside six of the colors below.
- Notice three colors of the 'server compute' co-related items are 1) from the same shade, and 2) in the cool palette
- The other three unrelated items are 1) not of the same shade, and 2) from the warm palette
2) Resulting plot (for presentation purposes, some values were spoofed to show their contribution to the bar from a color perspective)
3) Fixed spacing
- Old (starting point before this PR)
=> Update colors for detail report legend

docs/cli.md
Links are wrong in main: https://github.com/triton-inference-server/model_analyzer/blob/main/docs/cli.md
Links work with the fix: https://github.com/triton-inference-server/model_analyzer/blob/tgerdes-fix-docs/docs/cli.md
=> Fix link to subcommand-analyze in docs

model_analyzer/plots/detailed_plot.py, model_analyzer/plots/simple_plot.py, model_analyzer/reports/report_manager.py, model_analyzer/result/run_config_measurement.py, tests/test_run_config_measurement.py
Added accessor function for getting MCM's PA parameters (from RCM) with unit testing.
Replaced private variable in plot and report files with this method.
=> Adding accessor function for PA params to RCM

model_analyzer/plots/plot_manager.py, model_analyzer/record/metrics_manager.py, model_analyzer/result/run_config_measurement.py, qa/L0_analyze/test.sh, qa/L0_output_fields/test.sh, qa/L0_results/test.sh, tests/common/test_utils.py, tests/test_run_config_measurement.py
Added model-name to RCM class with unit testing
Using model-name instead of key in plot manager
Visually verified that the detailed report pdf is working as intended:
=> Replace key with model-name in plot manager

model_analyzer/analyzer.py, model_analyzer/config/input/config_command_profile.py, model_analyzer/config/run/model_run_config.py, model_analyzer/config/run/run_config.py, model_analyzer/model_manager.py, model_analyzer/perf_analyzer/perf_analyzer.py, model_analyzer/plots/plot_manager.py, model_analyzer/plots/simple_plot.py, model_analyzer/record/metrics_manager.py, model_analyzer/reports/report_manager.py, model_analyzer/result/result_manager.py, model_analyzer/result/results.py, model_analyzer/result/run_config_measurement.py, model_analyzer/result/run_config_result.py, model_analyzer/state/analyzer_state_manager.py, qa/L0_analyze/test.sh, qa/L0_output_fields/test.sh, qa/L0_results/test.sh, tests/common/test_utils.py, tests/test_analyzer.py, tests/test_model_config_generator.py, tests/test_model_manager.py, tests/test_perf_analyzer.py, tests/test_report_manager.py, tests/test_results.py, tests/test_run_config.py, tests/test_run_config_generator.py, tests/test_run_config_measurement.py, tests/test_run_config_result_comparator.py
Update ResultManager to store tuple using RunConfig instead of ModelConfig
RunConfig new functions:
- cpu_only()
- models_name()     : for base model names
- model_variants_name()  : for model variants
- from_dict()
ModelRunConfig new functions:
- model_variant_name()
- from_dict()
Updated ModelManager.run_model() to ModelManager.run_models(), which can handle single or multiple concurrent models
Refactor PerfAnalyzer to prep for MPI changes
Update MetricsManager.execute_run_config() and MetricsManager.profile_models() to handle multi-model
=> Prep for MPI PA integration

model_analyzer/analyzer.py, model_analyzer/config/generate/perf_analyzer_config_generator.py, model_analyzer/config/generate/run_config_generator.py, model_analyzer/config/input/config_command_profile.py, model_analyzer/perf_analyzer/perf_analyzer.py, model_analyzer/record/metrics_manager.py, qa/L0_multi_model_profile/check_results.py, qa/L0_multi_model_profile/test.sh, qa/L0_multi_model_profile/test_config_generator.py, tests/common/test_utils.py, tests/test_cli.py, tests/test_perf_analyzer.py
Enable multi-model (--run-config-profile-models-concurrently-enable)
Added L0_multi_model_profile test
Updated PA get_cmd() for multi-model to use MPI
Updated auto_adjust_parameters() support to handle multi-model
=> Enable multi-model

model_analyzer/config/generate/automatic_model_config_generator.py
```
[Model Analyzer] Profiling resnet50_libtorch_config_2: client batch size=1, concurrency=64
[Model Analyzer] Profiling resnet50_libtorch_config_2: client batch size=1, concurrency=128
[Model Analyzer] No longer increasing concurrency as throughput has plateaued
[Model Analyzer] No longer increasing max_batch_size because throughput has plateaued
[Model Analyzer] Saved checkpoint to /opt/triton-model-analyzer/checkpoints/0.ckpt
```
=> Don't print plateau warning more than once

model_analyzer/record/metrics_manager.py, model_analyzer/result/model_config_measurement.py, model_analyzer/result/run_config_measurement.py, qa/L0_analyze/test.sh, qa/L0_output_fields/test.sh, qa/L0_results/test.sh, tests/common/test_utils.py, tests/test_model_config_generator.py, tests/test_model_config_measurement.py, tests/test_model_manager.py, tests/test_plot.py, tests/test_run_config_generator.py, tests/test_run_config_measurement.py, tests/test_run_config_result.py, tests/test_run_config_result_comparator.py
Add the following default values:
- All models equally weighted (in RunConfigMeasurement)
- ModelConfigs metrics are compared against using perf_throughput (in ModelConfigMeasurement)
Added an assertion to ensure that the correct number of model/metric weightings are set before any comparisons are done.
Updated failing unit tests.
=> Set default model and metric weightings to RCM/MCM classes

model_analyzer/config/generate/perf_analyzer_config_generator.py, model_analyzer/reports/report_manager.py, model_analyzer/result/model_config_measurement.py, model_analyzer/result/result_manager.py, model_analyzer/result/run_config_measurement.py, model_analyzer/result/run_config_result.py, model_analyzer/result/run_config_result_comparator.py, tests/test_model_config_measurement.py, tests/test_run_config_measurement.py
The issue is that because we use a minheap, the `__lt__` methods in MCM/RCM have to return the opposite of the users expected value. This creates problems if the user does comparisons outside of the heap.
To solve this I inverted the data going "in to/out of" the heap. This allows me to reverse the __lt__ methods in MCM/RCM. I've fixed the usages in perf_config_generator and report_manager and updated comments/unit tests.
=> Invert polarity of data stored in minheap

model_analyzer/config/generate/automatic_model_config_generator.py, model_analyzer/config/generate/perf_analyzer_config_generator.py, model_analyzer/plots/detailed_plot.py, model_analyzer/plots/simple_plot.py, model_analyzer/reports/report_manager.py, model_analyzer/result/model_config_measurement.py, model_analyzer/result/run_config_measurement.py, tests/test_run_config_measurement.py
Replace all calls to get_metric/get_metric_value() with gpu/non-gpu specific methods.
Remove these methods from RunConfigMeasurement
=> Replace get metric value calls

model_analyzer/config/generate/automatic_model_config_generator.py, model_analyzer/config/generate/base_model_config_generator.py, model_analyzer/config/generate/generator_factory.py, model_analyzer/config/generate/manual_model_config_generator.py, model_analyzer/config/generate/model_run_config_generator.py, model_analyzer/config/generate/model_variant_name_manager.py, model_analyzer/config/generate/run_config_generator.py, model_analyzer/constants.py, tests/test_model_config_generator.py, tests/test_model_variant_name_manager.py, tests/test_run_config_generator.py
Make sure that if the same configuration is reused, it will have the same name. This is especially useful for multi-model.
=> consistent model variant naming

Dockerfile
To best ensure the security and reliability of our RPM and Debian package repositories, NVIDIA is updating and rotating the signing keys used by apt, dnf/yum, and zypper package managers beginning April 27, 2022. Failure to update your repository signing keys will result in package management errors when attempting to access or install packages from CUDA repositories.
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212771
=> GPG CUDA Linux Repository Key Rotation

model_analyzer/analyzer.py, model_analyzer/entrypoint.py, model_analyzer/result/result_manager.py, model_analyzer/state/analyzer_state_manager.py, tests/test_analyzer.py, tests/test_state_manager.py
These changes will cause an exception to be raised if we detect a missing checkpoint or if the checkpoint does not contain the model(s) specified by the user on the CLI.
Here is the new output if no checkpoint exists:
Here is the new output if the checkpoint exists, but the model is not found:
=> Stop analyze/report if no/bad checkpoint

model_analyzer/config/generate/base_model_config_generator.py, model_analyzer/config/generate/manual_model_config_generator.py, model_analyzer/record/metrics_manager.py, model_analyzer/reports/report_manager.py
- If no CPU metrics, do not print "Max CPU Memory Usage" to table for both detailed and summary reports
- If no CPU metrics, do not print "RAM usage vs latency" plot for both detailed and summary reports
- Fixed a bug where "cpu_only" was not put into checkpoint properly, and thus the GPU plots were printed for CPU cases
- Reduce the number of times the CPU warning is printed
I manually compared the resulting reports of all 16 combinations of the following {detailed vs summary}{online vs offline}{model run on cpu vs gpu}{cpu metrics being collected vs not} and confirmed all changes are as expected.
Showing the table and chart no longer being printed when CPU info not gathered:
Showing the cpu_only bug fix that now correctly shows CPU information and charts instead of GPU:
Before and after …
=> Remove cpu ram from reports when not collected

model_analyzer/triton/client/client.py, tests/test_cpu_monitor.py, tests/test_dcgm_monitor.py, tests/test_remote_monitor.py, tests/test_triton_client.py
I've added a configurable sleep time to the wait_for methods, that lowers this from 1 second to 100ms for unit tests. 
I've also reduced the monitoring times where possible. 
The end result is that unit test time drops from 105 to 76 seconds!
=> Reduce wall clock time for unit tests - configurable sleep timer

docs/install.md, docs/quick_start.md
Updated the install document to recommend the Triton SDK with docker launch mode
Updated the quick start document to use Triton SDK with docker launch mode
=> Recommend SDK in install and quick start

docs/quick_start.md
Running `git remote add` command requires specifying a shortname for the remote url. Added shortname `origin`.
=> Minor update for quick start guide

experiments/config_command_experiment.py, experiments/evaluate_config_generator.py, experiments/experiment_config_command_creator.py, experiments/generator_experiment_factory.py, experiments/main.py
Added ability to set algorithm-specific knobs on the experiments command line.
For example, standard profile option of max model batch size can be specified:
`python3 main.py --model-name resnet50_libtorch --generator RunConfigGenerator --run-config-search-max-model-batch-size 2`
Also, new options for Undirected algorithm can be set:
`python3 main.py --model-name resnet50_libtorch --generator UndirectedRunConfigGenerator --magnitude 5`
=> Expose experiment knobs

model_analyzer/triton/server/server_config.py, model_analyzer/triton/server/server_factory.py, tests/test_triton_server_factory.py
There were two bugs in setting of metrics-interval-ms:
1: the triton config class in MA didn't recognize metrics-interval-ms as a valid option
2: the value was being set when we were using local_gpu_monitor, when it should have been set when we were NOT using local_gpu_monitor
Fixed those bugs and added unit testing around the TritonServerFactory
=> Fix bug and add testing for setting metrics-interval-ms

model_analyzer/perf_analyzer/perf_analyzer.py, tests/mocks/mock_perf_analyzer.py, tests/test_perf_analyzer.py
When PA aborts with GPU OOM, each of its threads dumps a huge error string.  Piping the result of STDERR was overflowing the buffer, resulting in the subprocess to hang.
The red warning below in the Popen documentation tells us that this can happen. It says that the solution is to use communicate(), but communicate blocks until finished and the code needs to continue gathering CPU utilization
The solution is to pipe both stderr and stdout to a (temporary) file
=> Fix issue where PA would hang until timeout

docs/cli.md, docs/config.md, docs/quick_start.md, model_analyzer/config/input/config_command_profile.py
Add link to Triton documentation of Model Repository.
Remove incorrect mention of pickle.
=> Update documentation for model repository

model_analyzer/config/run/model_run_config.py, model_analyzer/perf_analyzer/perf_config.py, tests/test_run_config.py
Removes measurement-request-count from PA representation field. This way on a checkpoint restore we will treat find/match on this entry even if a non-default MRC was needed.
=> Remove measurement-request-count from representation

model_analyzer/analyzer.py, qa/L0_perf_analyzer/test.sh, qa/L0_perf_analyzer/test_config_generator.py
The test has always been "failing" because streaming is not allowed with http, but changes to run analyze in the profile step exposed the failure.
This fixes the test to run properly and actually test what it was intended to test.
=> Fix failing L0 PA test

docs/config.md, docs/install.md, docs/metrics.md, model_analyzer/analyzer.py, model_analyzer/record/metrics_manager.py, model_analyzer/result/model_config_measurement.py, model_analyzer/result/result_table_manager.py, model_analyzer/triton/server/server_docker.py
- Remove mention of DCGM requirement in docs
- Downgrade "stopped triton server" print to debug for docker mode (just like it is for local mode)
- Only print "CPU metrics are not being collected" once
- Refactor csv printing. Don't print files with no data
- Removed warning about "No non-gpu metric", as it provided no value
I did NOT fix the following warning, because I think it is legit as it comes from the options of what fields to print in the csv files:
- Analysis step printed a ton of warnings about GPU and Server output fields gpu_used_memory, gpu_utilization, and gpu_power_usage
=> Clean up cpu-only mode

model_analyzer/config/generate/automatic_model_config_generator.py, tests/test_model_config_generator.py, tests/test_model_manager.py
If max_batch_size is not specified or is set to 0 in the default config, do not sweep over max_batch_size, and do not enable dynamic batching.
=> Don't enable dynamic batching if no max_batch_size in config

model_analyzer/model_manager.py, model_analyzer/record/metrics_manager.py, qa/L0_perf_analyzer/test.sh
When calling PA, if the model config is the same as the previous one (and we are only changing PA attributes like concurrency) then do not tear down the server and start from scratch. Instead utilizing the server that is already up with the proper model config loaded.
=> Skip unload/reload and server restart

model_analyzer/triton/model/model_config.py
Otherwise all edits we make to the returned config actually changed the cached version of the base config
=> BugFix: Return a copy of cached config instead of a reference

docs/checkpoints.md, docs/cli.md, docs/config.md, docs/quick_start.md
Updated CLI, config, and quick start documentation now that profile & analysis are combined.
I have still left the documentation for analysis in, but have indicated that it's usage has been combined with profile and we will be deprecating its usage in the near future.
=> Documentation updates due to profile-analysis being combined

docs/install.md, docs/quick_start.md
wkhtmltopdf is available in sdk container and will be installed with a wheel or pip install. There is no need to mention it in any docs
=> Remove wkhtmltopdf requirement from docs

model_analyzer/triton/server/server_docker.py
**Old code** would look like it was hanging while it was pulling the container the first time:
First time running when container image hasn't been pulled yet:
```
15:16:30 [Model Analyzer] Profiling server only metrics...
15:18:26 [Model Analyzer] DEBUG: Triton Server started.
```
Second time:
```
15:24:29 [Model Analyzer] Profiling server only metrics...
15:24:30 [Model Analyzer] DEBUG: Triton Server started.
```
**New code** will call out the pull, so it is clear why there is a delay
First time running when container image hasn't been pulled yet:
```
15:47:14 [Model Analyzer] Starting a Triton Server using docker
15:47:14 [Model Analyzer] Pulling docker image nvcr.io/nvidia/tritonserver:22.07-py3
15:49:02 [Model Analyzer] No checkpoint file found, starting a fresh run.
15:49:02 [Model …
```
=> Explicitly pull the container in docker mode

model_analyzer/config/generate/coordinate.py, model_analyzer/config/generate/coordinate_data.py, model_analyzer/config/generate/neighborhood.py, model_analyzer/config/generate/quick_run_config_generator.py, tests/test_coordinate.py
* Fix or add missing type hints
* Make Coordinate class to be iterable for compatibility with tuple type hints
* Avoid `round` operator overloading in Coordinate class since Python expects round operator to return integer
* Fix test case
=> Fix type checking failures in quick search algo

model_analyzer/config/generate/neighborhood.py, tests/test_neighborhood.py
* Adjust the clipping method so that it preserves the direction of the step vector
* Add test cases
=> Preserve direction when clipping step vector

experiments/evaluate_config_generator.py, model_analyzer/config/generate/coordinate_data.py, model_analyzer/config/generate/neighborhood.py, model_analyzer/config/generate/quick_run_config_generator.py, model_analyzer/model_manager.py, tests/test_neighborhood.py
* Allow quick algo to adjust search based on constraints provided
* Compare constraints when both home and neighbors are all failing the constraints ([#489](https://github.com/triton-inference-server/model_analyzer/pull/489))
* Add test cases
=> Enable constraints-aided search in quick algo

model_analyzer/reports/report_manager.py, tests/test_report_manager.py
Old code did not specify number of GPUs, so it looked like only one GPU was running in the reports.
New code cleans that up:
=> Updating printing of GPU names and max memory

experiments/checkpoint_experiment_data.py, experiments/config_command_experiment.py, experiments/evaluate_config_generator.py, experiments/experiment_config_command_creator.py, experiments/experiment_data.py, experiments/experiment_evaluator.py, experiments/generator_experiment_factory.py, experiments/scripts/sweep_checkpoints.py
New script to run the experiment script on all models in all checkpoints in a directory (recursively) 
Also, make the following updates to the experiment script:
- support for running experiment without default config (it can get it from the checkpoint)
- support for custom constraints and objectives
- support for exponential instance count
- debug print throughput/latency map
=> Sweep experiments script

model_analyzer/config/generate/coordinate.py, model_analyzer/config/generate/neighborhood.py, model_analyzer/config/generate/quick_run_config_generator.py, tests/test_neighborhood.py
Results show it is slower, but more accurate, as expected:
**Baseline (without these changes):**
normal Average/Median/Mode percentiles = 0.93 / 0.98 / 1.00
normal Average/Median/Mode measurements = 11.85 / 11.50 / 7.00
normal: 10 out of 128 are below the cutoff of 70.0%:
latency_budget Average/Median/Mode percentiles = 0.94 / 0.97 / 1.00
latency_budget Average/Median/Mode measurements = 10.47 / 10.00 / 4.00
latency_budget: 4 out of 127 are below the cutoff of 70.0%:
min_throughput Average/Median/Mode percentiles = 0.94 / 1.00 / 1.00
min_throughput Average/Median/Mode measurements = 5.55 / 5.00 / 4.00
min_throughput: 9 out of 125 are below the cutoff of 70.0%:
**New (with these changes):**
normal Average/Median/Mode percentiles = 0.95 / 0.99 / 1.00
normal Average/Median/Mode measurements …
=> Add slow mode support

experiments/config_command_experiment.py, experiments/evaluate_config_generator.py, experiments/experiment_file_writer.py, experiments/main.py, experiments/start_profiles.sh, model_analyzer/config/generate/neighborhood.py, model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py, model_analyzer/config/generate/quick_run_config_generator.py, model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/config/generate/search_config.py, model_analyzer/constants.py, tests/test_neighborhood.py, tests/test_quick_run_config_generator.py, tests/test_search_config.py
- Updated the way that measurements and vectors are used to calculate the step vector
- Added a translation function to convert resulting step vector into actual step vector (instead of relying on magnitude, clipping, and clamping)
- Removed the concept of magnitude
Almost no change in the results, but gives us more control over tweaking step direction and size
**Old (current main with slow mode support):**
normal Average/Median/Mode percentiles = 0.95 / 0.99 / 1.00
normal Average/Median/Mode measurements = 13.23 / 12.00 / 7.00
normal: 7 out of 128 are below the cutoff of 70.0%:
latency_budget Average/Median/Mode percentiles = 0.97 / 1.00 / 1.00
latency_budget Average/Median/Mode measurements = 11.74 / 10.00 / 10.00
latency_budget: 2 out of 127 are below the cutoff of 70.0%: …
=> Update step calculation. Add translation of vector instead of magnitude

model_analyzer/config/generate/coordinate_data.py, model_analyzer/config/generate/neighborhood.py, model_analyzer/config/generate/quick_run_config_generator.py, tests/test_coordinate_data.py, tests/test_neighborhood.py
No longer create a coordinateData inside of neighborhood. Instead, pass it in. Without this change, we were ignoring some measurements and wasting time gathering new different measurements.
Also, update some CoordinateData concepts around visiting/measuring to differentiate between home visits vs random coordinate measurements
Results: Significant drop off in the number of measurements taken, but much of this was probably fake savings (we would re-measure a coordinate, but the ResultData had a cache so it didn't cost us anything to re-measure). However, this still looks really good.
**Old Results (current main with slow mode changes):**
normal Average/Median/Mode percentiles = 0.95 / 0.99 / 1.00
normal Average/Median/Mode measurements = 13.23 / 12.00 / 7.00
normal: 7 out of 128 are below …
=> only use one coordinate data

model_analyzer/analyzer.py, model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py, model_analyzer/result/result_manager.py
Destroying and rebuilding the result heaps after profile completes
Also changed to use the correct number of configs per model when sweeping concurrency.
I've verified this works with fresh runs for quick searches of add_sub and resnet, as well as a sequential run of resnet+add_sub
=> Rebuilding heaps after profile completes

model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py
Fix issue where quick search was not sweeping concurrencies for top configs
=> Fix quick search concurrency sweep

model_analyzer/triton/server/server_docker.py, qa/L0_custom_ops/test.sh, qa/L0_custom_ops/test_config_generator.py
Fix for https://github.com/triton-inference-server/model_analyzer/issues/527
The triton-server-environment was correctly passed to triton in docker mode on the first launch, but was deleted and thus would be empty on subsequent launches of triton server
=> Fix bug in docker-mode ENV

Dockerfile, README.md, docs/cli.md, docs/config.md, docs/config_search.md, docs/install.md, docs/metrics.md, docs/quick_start.md, qa/L0_doc_links/mkdocs.yml, qa/L0_doc_links/test.sh
Fixed all broken doc links
Added a test to protect against links ever breaking again
Tweaked the perf_analyzer_flags section (for https://github.com/triton-inference-server/model_analyzer/issues/529)
=> Fix broken doc links. Add test to protect doc links

model_analyzer/config/input/config_command.py, tests/test_config.py
If the user specifies `profile-models` on both the CLI and in the YAML we should error and force the user to remove one of these specifications.
Unlike, other options which might have a use case where the user wants to override certain  YAML values on the CLI, there is no use case where the user would want to override `profile-models` on the CLI.
This has bitten multiple engineers and wasted countless person-hours debugging why the YAML settings were not being recognized.
=> Error if profile-models is specified on both CLI and in the YAML

model_analyzer/config/input/config_command.py, tests/test_cli.py, tests/test_config.py
Checks that quick search is specified when running multi-model and than no search or list values are used when in quick search.
Added unit testing and refactored the code in config command.
=> Multi-model and Quick Search Config Checking

requirements.txt
Update gevent version to pick up the following fix:
https://github.com/gevent/gevent/pull/1864
I confirmed this makes the following warnings go away:
```
/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
return self._float_to_str(self.smallest_subnormal)
```
=> Update gevent version

README.md, docs/README.md
Added the video link to the new README
Also, added an `Examples and Tutorials` section to top-level README and moved our quick start guide into there
=> Add README to doc folder

docs/install.md, model_analyzer/reports/report_factory.py
Despite what https://github.com/triton-inference-server/model_analyzer/pull/493 says, wkhtmltopdf is NOT included in the wheel install. Thus, adding back in clearer directions for the case where the user runs without it installed.
Also, making sure the warning only prints once per run.
=> Fix PDF warning to include command

model_analyzer/reports/report_manager.py, tests/test_report_manager.py
Noticed a bug in the constraints message in our result summary for multi-model runs:
Root caused an fixed it:
I've also added unit testing to ensure this doesn't break in the future and checked that single model is still printing as intended (just the constraint w/o the test name)
=> Fixing constraints statement for multi-model

model_analyzer/config/generate/quick_run_config_generator.py, tests/common/test_utils.py, tests/test_quick_run_config_generator.py
Fix issue where quick search's default config generation wasn't respecting the PA flags set by the user
=> Add PA flag support to quick search's default config

model_analyzer/config/generate/base_model_config_generator.py, model_analyzer/config/generate/model_variant_name_manager.py, model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py, model_analyzer/config/generate/quick_run_config_generator.py, model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/config/run/model_run_config.py, model_analyzer/model_manager.py, model_analyzer/result/result_manager.py, model_analyzer/triton/model/model_config.py, tests/test_model_variant_name_manager.py, tests/test_quick_run_config_generator.py
Logic to create the default config in the Quick RCG for an ensemble model.
This also includes changes to the Model Variant Name Manager.
I have a new unit test in the QRCG and have run this with an ensemble model and verified that we are generating the default configs correctly.
=> Ensemble default config generation

model_analyzer/record/metrics_manager.py
The creates and loads the submodel variants for ensemble models. No unit testing for this, but here's the output log from an ensemble run (preprocess and resnet50_trt are the submodel names):
```
22:13:19 [Model Analyzer] Initializing GPUDevice handles
22:13:20 [Model Analyzer] Using GPU 0 NVIDIA TITAN RTX with UUID GPU-8557549f-9c89-4384-8bd6-1fd823c342e0
22:13:20 [Model Analyzer] WARNING: Overriding the output model repo path "/swdev/profile_outputs/"
22:13:20 [Model Analyzer] Starting a local Triton Server
22:13:20 [Model Analyzer] No checkpoint file found, starting a fresh run.
22:13:20 [Model Analyzer] Profiling server only metrics...
22:13:20 [Model Analyzer] DEBUG: Triton Server started.
22:13:30 [Model Analyzer] DEBUG: Stopped Triton Server.
22:13:30 [Model Analyzer] 
22:13:30 …
```
=> Loading ensemble submodels into Triton

docs/config_search.md, model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py, model_analyzer/config/generate/quick_run_config_generator.py, model_analyzer/config/input/config_command.py, model_analyzer/config/input/config_field.py, tests/test_config.py, tests/test_quick_run_config_generator.py
This change enables the user to specify a min/max concurrency, model batch size or instance count in quick search.
Added unit testing to cover all relevant cases and have tried this out with an ensemble model and confirmed it is working.
=> Allow min/max setting in quick search

model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/config/input/config_command.py, model_analyzer/model_manager.py, tests/test_model_manager.py
This checks for the two illegal inputs the user could provide for an ensemble model:
- More than one model being profiled
- Brute force search mode
=> Checking for illegal inputs from user for an ensemble model

model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/config/run/model_run_config.py, tests/test_run_config.py
Adds in the necessary checks to see if all ensemble submodels are legal w/ unit testing.
Also:
- fixes a bug in RCG that was not properly setting the batch size dimension for ensemble models
- fixes formatting issues from Sai's check-in.
=> Add is_legal_combination check for ensemble submodels

model_analyzer/reports/report_factory.py
Adds a space in `wkthmltopdf` error message:
Before:
```
of pdf becausewkhtmltopdf is not installed.
```
After:
```
of pdf because wkhtmltopdf is not installed.
```
=> Fix wkhtmltopdf error message

README.md, docs/config_search.md
Adding ensemble model support to our documentation. Will file a separate story to add an example ensemble to our documentation when we find a suitable model. I've also removed the `early access` tag from multi-model.
=> Add Ensemble documentation

docs/config.md, docs/config_search.md, docs/quick_start.md
Overhaul of `config_search.md` to include more examples and be more explicit about our different modes, how they operate, and what options exist in each mode.
=> Rewrite config_search.md

docs/cli.md, docs/quick_start.md, model_analyzer/analyzer.py, qa/L0_results/test.sh, tests/test_analyzer.py
- Remove message in profile step that instructs user about running detail reporting
- Add error message in detailed report step when multiple different models are detected
Needed to modify **L0_results** test to only check for a single model config
=> Multi-model detailed reporting changes

docs/config_search.md
Adds caveat that we don't support submodel `cpu_only` for ensembles
Fixes typos pointed out by external user
=> Add caveat to ensemble documentation

model_analyzer/config/generate/quick_plus_concurrency_sweep_run_config_generator.py, model_analyzer/config/generate/quick_run_config_generator.py, model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/config/run/model_run_config.py, model_analyzer/model_manager.py, model_analyzer/record/metrics_manager.py, results/metrics-server-only.csv, tests/test_model_manager.py, tests/test_quick_run_config_generator.py
Creates BLS composing models for the default config. Limited unit testing here, but more will be added once the non-default configs are generated.
In addition I have run this with a BLS model and confirmed that we are sending/load configs to PA/tritonserver correctly (but, I needed to hack the BLS composing configs name - which is the follow-on story to this)
=> Logic to create BLS composing models for default config

model_analyzer/config/generate/base_model_config_generator.py, model_analyzer/record/metrics_manager.py, model_analyzer/triton/model/model_config.py, tests/test_model_config.py
BLS composing configs cannot mutate their names. This change creates a directory using the original composing model name and changes the config.pbtxt to use this as the model name when loading on the tritonserver.
=> Create unchanged BLS composing model output directory

workflows/codeql.yml
Update the cron format to make codeql static analysis run Monday-Saturday at 1am UTC (so 6pm PST, Sunday-Friday).
=> Update codeql static analysis to run daily

model_analyzer/config/generate/run_config_generator_factory.py, tests/test_quick_run_config_generator.py
Added a unit test to check this and also fixed a unit test that was mistakenly creating an ensemble in a composing model.
=> Check to ensure composing models do not contain an ensemble

docs/config.md, docs/config_search.md
Most documentation changes went in with the new config/CLI options.
Not sure where else this needs to be documented, other than in our release notes.
=> Adding request rate doc to config search

model_analyzer/result/concurrency_search.py, qa/L0_quick_search/test.sh
Adding  `--latency-budget 10` to **L0_quick_search** will enable a binary search.
This exposed some bugs in the code around cases where PA doesn't return a result and we add `None` to the ConcurrencySearch's RCM list.
I've updated the code to check and deal with None.
=> Add binary search to L0_quick_search

docs/config.md, model_analyzer/config/generate/model_profile_spec.py, model_analyzer/config/input/config_command_profile.py, model_analyzer/model_manager.py, tests/test_cli.py, tests/test_model_manager.py, tests/test_quick_run_config_generator.py
Adds a new config option `--cpu-only-composing-models` which asks for a list of composing models that will be profiled as `cpu_only`.
Added checks and unit testing to ensure this can only be specified if the model is an ensemble.
When the model profile is created will now set `cpu_only` if the composing model name is in the new list.
Added unit testing and ran a live test to confirm this is working as intended.
=> Add `cpu_only` option for ensemble composing models

model_analyzer/analyzer.py, model_analyzer/record/metrics_manager.py, model_analyzer/triton/client/client.py, model_analyzer/triton/client/grpc_client.py, model_analyzer/triton/model/model_config.py, model_analyzer/triton/server/server.py, model_analyzer/triton/server/server_docker.py, model_analyzer/triton/server/server_local.py, tests/mocks/mock_server.py, tests/mocks/mock_server_local.py, tests/test_triton_client.py, tests/test_triton_server.py
Will now scan the triton_output log looking for `Unexpected argument:` and will terminate the `wait_for_server_ready()` method early (saving about 50 retries and around 15 seconds of user time).
Will now print out the failure message rather than the generic client error.
Have tested this live and added a unit test to check this case.
Note: We will now delete an existing log file (rather than append) to ensure that any error messages seen are for the current run.
=> Detect when tritonserver fails to launch

model_analyzer/analyzer.py, model_analyzer/constants.py, model_analyzer/record/metrics_manager.py, model_analyzer/triton/client/client.py
Current behavior only prints PA errors to stdout. 
The new behavior will capture PA errors that occur during profiling to a log file, inform the user that errors occurred, and point them to the new log file.
The log file contains (per PA error) the configuration name, PA command line. and PA error.
There is no unit testing for this (as neither metrics manager or analyzer has a unit test env), but I've run this on live tests that have known PA errors and observed the log file being properly created.
=> Capture PA errors in a log file

model_analyzer/config/input/config_command_profile.py, tests/mocks/mock_os.py, tests/test_report_manager.py
Instead of erroring, we will now create an export path for the user if it doesn't exist, but it's parent directory does. 
We will still error in the case where the export path is a file or if multiple levels of directories need to be created.
=> Create export_path if it doesn't exist

model_analyzer/monitor/cpu_monitor.py, model_analyzer/monitor/dcgm/dcgm_monitor.py, model_analyzer/monitor/monitor.py, model_analyzer/monitor/remote_monitor.py, model_analyzer/record/metrics_manager.py, qa/L0_ssl_https/test.sh
Will now raise an error in local or docker mode if no GPU records are returned from the tritonserver before the first measurement is taken.
=> Detect and handle invalid metrics url

model_analyzer/monitor/remote_monitor.py, model_analyzer/record/metrics_manager.py
Fix wheeltamer failures caused by requests.get not having a timeout
=> Add timeout to requests.get calls

model_analyzer/triton/server/server_docker.py
See [https://github.com/triton-inference-server/model_analyzer/issues/725](https://github.com/triton-inference-server/model_analyzer/issues/725) for details on the failure.
The solution is to implement a temp log file (to match the code in `server_local.py`)
=> Fix error in docker mode when triton output path is not specified

docs/config_search.md, model_analyzer/config/generate/quick_run_config_generator.py, model_analyzer/config/input/config_command.py, tests/test_config.py, tests/test_quick_run_config_generator.py
In brute search mode, we toggle between automatic and manual search based on the presence of `model_config_parameters`.
In quick search mode, we currently ignore any model config parameters and silently overwrite them when generating configurations.
This is remedied in two ways:
1. Added a config check which checks that only a single configuration of parameters can be generated (else it tells the user to run in brute search mode)
2. Quick search parameters are now additive and will preserve the original model config parameters set by the user
Unit testing was added to check for these cases and documentation is updated to reflect this restriction in quick search.
=> Quick search preserves model config parameters

model_analyzer/triton/model/model_config.py, tests/test_model_config.py
Distutils is being deprecated. Replace its usage with shutil (used elsewhere in Model Analyzer).
Related server PR: https://github.com/triton-inference-server/server/pull/6190
Related client PR: https://github.com/triton-inference-server/client/pull/382
=> Remove deprecated distutils

docs/bls_quick_start.md, docs/ensemble_quick_start.md, docs/launch_modes.md, docs/mm_quick_start.md, docs/quick_start.md
Remove restrictions on remote mode profiling.
Remove absolute path restriction in docker mode (since we are now using the API to pass in a configuration to the tritonserver).
=> Remote and Docker mode changes

model_analyzer/analyzer.py, model_analyzer/entrypoint.py, model_analyzer/triton/model/model_config.py
Currently, in all modes we require a path to the model repository. This is no longer necessary for remote mode, as we are now loading the models via API with the tritonserver in explicit mode, therefore the tritonserver already needs to be pointed to the model directory (on the remote machine) and MA doesn't need access (only the model name).
This story also fixed/refactoring the error messages around creating the default configuration.
=> Remove requirement that remote mode have a model repository path

model_analyzer/config/generate/perf_analyzer_config_generator.py, model_analyzer/config/input/config_command.py, model_analyzer/config/input/config_command_report.py, model_analyzer/perf_analyzer/perf_config.py, tests/test_config.py
Add in checks for illegal combination of options when running an LLM model through MA.
=> Adding illegal LLM checks w/ unit testing + some minor cleanup

model_analyzer/record/metrics_manager.py
Currently we are not outputting anything about the configuration when we are in remote mode (as we don't have access to the model). This change is to output the `config.pbtxt` variant for each configuration MA creates.
=> Output config.pbtxt when in remote mode

.pre-commit-config.yaml, Dockerfile, model_analyzer/device/gpu_device_factory.py, model_analyzer/monitor/dcgm/DcgmDiag.py, model_analyzer/monitor/dcgm/DcgmFieldGroup.py, model_analyzer/monitor/dcgm/DcgmGroup.py, model_analyzer/monitor/dcgm/DcgmHandle.py, model_analyzer/monitor/dcgm/DcgmJsonReader.py, model_analyzer/monitor/dcgm/DcgmReader.py, model_analyzer/monitor/dcgm/DcgmStatus.py, model_analyzer/monitor/dcgm/DcgmSystem.py, model_analyzer/monitor/dcgm/common/__init__.py, model_analyzer/monitor/dcgm/common/dcgm_client_cli_parser.py, model_analyzer/monitor/dcgm/common/dcgm_client_main.py, model_analyzer/monitor/dcgm/dcgm_agent.py, model_analyzer/monitor/dcgm/dcgm_collectd_plugin.py, model_analyzer/monitor/dcgm/dcgm_errors.py, model_analyzer/monitor/dcgm/dcgm_field_helpers.py, model_analyzer/monitor/dcgm/dcgm_fields.py, model_analyzer/monitor/dcgm/dcgm_fields_collectd.py, model_analyzer/monitor/dcgm/dcgm_fields_internal.py, model_analyzer/monitor/dcgm/dcgm_fluentd.py, model_analyzer/monitor/dcgm/dcgm_prometheus.py, model_analyzer/monitor/dcgm/dcgm_structs.py, model_analyzer/monitor/dcgm/dcgm_telegraf.py, model_analyzer/monitor/dcgm/dcgmvalue.py, model_analyzer/monitor/dcgm/denylist_recommendations.py, model_analyzer/monitor/dcgm/pydcgm.py
Should merge together with: https://github.com/triton-inference-server/server/pull/6515
=> Update DCGM version to 3.2.6

Dockerfile, requirements.txt
Protobuf was magically coming from the client repo, and was recently removed. MA should be making sure it exists, as it has code that uses it. This change fixes that issue.
=> Fix protobuf dependency

model_analyzer/plots/detailed_plot.py
Thanks to https://github.com/triton-inference-server/model_analyzer/issues/804 for the suggestion, the bars on the detailed plots will now have colors that are compatible with colorblind.
=> Update plot colors to be colorblind compatible

model_analyzer/record/metrics_manager.py
Before this change, there was no way for Model Analyzer to load ensemble composing models via the API. This meant that they all defaulted to auto-complete configs. Now (with a required change to Triton) they can be loaded and won't be overwritten when the main ensemble config is loaded.
Fixes https://github.com/triton-inference-server/model_analyzer/issues/791
Needs this change to work: https://github.com/triton-inference-server/core/pull/304
=> Fix loading of composing models for ensembles

model_analyzer/config/generate/quick_run_config_generator.py, model_analyzer/triton/model/model_config.py, tests/test_model_config.py, tests/test_quick_run_config_generator.py
Updated unit test to check for this case and here's a run with the new formula showing that concurrency is set to 16 (max batch size is 8, instance count is 1) for the default config:
=> Update QRCG to set concurrency for default config

model_analyzer/analyzer.py, model_analyzer/triton/client/grpc_client.py, model_analyzer/triton/client/http_client.py, model_analyzer/triton/server/server_factory.py
Removed the incorrect warning in `server_factory.py` (we now have control of the model in remote mode).
The check for models already loaded was incorrect. The repository index is just a list of models that could be loaded, not what is currently loaded. 
After getting the list of potential models, I've added a call to `is_model_ready()` which will only return true if the model is actually loaded. 
No easy way to unit test this (it probably needs an L0, but that seems overkill for a warning message), but I have run it locally and confirmed that the warning messages both go away and then come back if I load a model on the server before running MA.
=> Fix incorrect remote mode warnings

model_analyzer/triton/server/server_config.py
Updated and reorganized the Server Arg Keys. You can find compare this to the current list of keys by running 'tritonserver --help`.
=> Updating Triton Server Arg Keys

model_analyzer/config/input/config_command_profile.py
During preprocessing, Model Analyzer checks whether request rate and concurrency are both missing if "run config search" is disabled. However, self.request_rate_ and self.concurrency_ are not set in the code, so the code always sets a concurrency value of 1. This results in an error if request-rate is provided with "run config search" disabled.
Move this check later to when the provided parameters are being checked and default values are set. Use the user-provided values and default values to determine whether concurrency and request-rate are set before using a default value for concurrency.
Fixes #838.
=> Move MA concurrency and request-rate check to autofill

model_analyzer/config/input/config_command_profile.py, model_analyzer/config/input/config_defaults.py, tests/test_config.py
Created a new set of output fields for LLM and switch from the default to this (with unit testing) when the user specifies that the `model type` is LLM
=> Adding new output fields for LLM

model_analyzer/perf_analyzer/perf_analyzer.py, model_analyzer/perf_analyzer/perf_config.py, model_analyzer/record/metrics_manager.py, tests/test_perf_analyzer.py
Successfully profiled and checkpointed a a vLLM run through MA using genai-perf. Here is the resulting table output:
```
Models (Inference):
Model       Batch   Concurrency   Model Config Path          Instance Group   Max Batch Size   Satisfies Constraints   Throughput (infer/sec)   p99 Latency (ms)   p99 Inter Token Latency (ms)   p99 Time To First Token (ms)   Output Token Throughput (infer/sec)  
gpt2_vllm   1       1             gpt2_vllm_config_default   1:MODEL          0                Yes                     8.9                      117.0              11.3                           47704.6                        76192.3                              
Models (GPU Metrics):
Model       GPU UUID                                   Batch   Concurrency   Model Config Path …
```
=> Profiling model using genai-perf

model_analyzer/config/input/config_command_profile.py, tests/test_config.py
Adds option for Optuna as a search mode
=> Adding cli option for optuna search

model_analyzer/config/generate/config_parameter.py, model_analyzer/config/generate/config_parameters.py, tests/test_config_parameters.py
As part of the scaffolding for the new search we need to more cleanly define the parameters the user wants to search. A new dataclass (ConfigParameter) and the accessor class (ConfigParameters) have been created to cleanly handle user defined parameters.
Note: Usage of this in MA will be in a follow-on story
=> Class to hold info about parameters

model_analyzer/config/generate/optuna_plus_concurrency_sweep_run_config_generator.py, model_analyzer/config/generate/optuna_run_config_generator.py, model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/config/generate/search_parameter.py, model_analyzer/config/generate/search_parameters.py, model_analyzer/model_manager.py, tests/test_optuna_run_config_generator.py, tests/test_search_parameters.py
Connected up SearchParameters class in the OptunaRCG. Updated unit testing to reflect this and I've also run live tests which include searching `max_queue_delay` which is not possible via quick search.
=> Using SearchParameters in OptunaRCG

model_analyzer/config/generate/optuna_run_config_generator.py, model_analyzer/config/generate/search_parameters.py, tests/test_search_parameters.py
Adds support for client batch size. 
FYI, I had reversed the roles of `max_batch_size` and `batch_sizes` when I originally created the SearchParameters/Optuna classes. This is now fixed and is reflected in the classes and unit tests.
=> Adding support for client batch size

model_analyzer/analyzer.py, model_analyzer/config/generate/optuna_run_config_generator.py, model_analyzer/config/generate/search_parameters.py, model_analyzer/config/input/config_command_profile.py, tests/test_search_parameters.py
Composing models in a BLS can also have search parameters:
```
run_config_search_mode: optuna
use_concurrency_formula: True
profile_models: bls
bls_composing_models:
add:
model_config_parameters:
max_batch_size: [1, 4, 8]
dynamic_batching:
max_queue_delay_microseconds: [100, 200, 300]
sub:
model_config_parameters:
max_batch_size: [32, 64, 128]
dynamic_batching:
max_queue_delay_microseconds: [400, 500, 600]
```
This story adds support for this to the SearchParameters class (which is used by OptunaRCG).
=> Adding BLS composing models to SearchParameters

model_analyzer/analyzer.py, model_analyzer/config/generate/optuna_plus_concurrency_sweep_run_config_generator.py, model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/config/generate/search_parameters.py, model_analyzer/config/run/run_config.py, model_analyzer/model_manager.py, tests/test_analyzer.py, tests/test_model_manager.py, tests/test_optuna_run_config_generator.py, tests/test_search_parameters.py
I've split the BLS OptunaRCG work into two stories to make it easier to review. 
This first story contains all the code changes to support BLS outside of the OptunaRCG class:
- Adds populate composing search parameters
- Adds missing check that batch size is supported when generating search parameters (discovered during BLS testing)
- PIpes composing_models all the way to OptunaRCG
- Updates unit-testing to have an actual ModelConfigProfileSpec (which is necessary to check if batch size exists in the protobuf)
- Adds new method to print the full variant name: `model_A::composing_model_A,composing_model_B...`
=> Adds BLS scaffolding to everything up to OptunaRCG

model_analyzer/analyzer.py, model_analyzer/config/generate/optuna_plus_concurrency_sweep_run_config_generator.py, model_analyzer/config/generate/optuna_run_config_generator.py, model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/config/generate/search_parameters.py, model_analyzer/config/input/config_command_profile.py, model_analyzer/config/run/run_config.py, model_analyzer/model_manager.py, tests/test_analyzer.py, tests/test_model_manager.py, tests/test_optuna_run_config_generator.py, tests/test_search_parameters.py
Adds support for BLS models to the Optuna search mode.
=>  Add BLS support to Optuna

model_analyzer/config/generate/optuna_run_config_generator.py, model_analyzer/config/input/config_command_profile.py, qa/L0_quick_search_multi_model/test.sh, tests/test_optuna_run_config_generator.py
Adds support for generating multi-model search profiles using the Optuna RCG including new unit testing to cover this code.
Here is the output from a live multi-model run I ran on my local machine using Optuna:
FYI, on my machine this took slightly longer than quick search, but produced a slightly better result (209% gain vs. 164% gain).
=> Add support for multi-model profiling to the Optuna RCG

model_analyzer/config/generate/optuna_plus_concurrency_sweep_run_config_generator.py, model_analyzer/config/generate/optuna_run_config_generator.py, model_analyzer/config/generate/run_config_generator_factory.py, model_analyzer/model_manager.py, model_analyzer/state/analyzer_state.py, tests/test_optuna_run_config_generator.py
Adds the seed used in Optuna to the checkpoint file. This seed is then read back anytime a checkpoint exists ensuring that we take the same path through the search algorithm for subsequent runs.
There's not an easy way to unit test this, but I have confirmed this works via a live run on my local machine (and we now have CI tests protecting Optuna).
=> Add Optuna Seed to Checkpoint

qa/L0_ensemble_model/check_results.py
I somehow accidently modified this file when I was checking in the new L0_optuna tests. The copyright issue is due to the `#!bin/bash`. This test is now passing locally and I will push this once it also passes on the CI.
=> Fixing copyright issue

docs/README.md, docs/config.md, docs/config_search.md, docs/metrics.md, docs/model_types.md
Point docs to new PA repo.
Server changes: https://github.com/triton-inference-server/server/pull/7488
Client changes: https://github.com/triton-inference-server/client/pull/771
PA changes: https://github.com/triton-inference-server/perf_analyzer/pull/21
DALI changes: https://github.com/triton-inference-server/dali_backend/pull/254
PyTriton changes: https://github.com/triton-inference-server/pytriton/pull/80
Tutorial changes: https://github.com/triton-inference-server/tutorials/pull/105
=> PA Migration: Doc Updates
